### ISSUE TITLE
PAS URLs have broken, no redirect

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-data#26]
URLs to the Portable Antiquities Scheme collection definitions have broken as the result of a change to the PAS website. The original URLs, in the form http://finds.org.uk/database/terminology/period/id/21, lead to a 404; the current address is https://finds.org.uk/datalabs/terminology/period/id/21. Need to know if we should fix all of these by hand.

**Comment by rybesh** [comment]
Portable Antiquities Scheme broke all their own URIs, so they really need to add a HTTP 301 permanent redirect from  `http://finds.org.uk/database/*` to ` http://finds.org.uk/datalabs/*`. I'm sure we're not the only ones who have old, now broken URIs. We can fix this in our dataset, but only because we're going to wipe and refresh the data in a few days anyway. If this request came in a week from today, it would be a "won't fix" (as it really should be, since it is the PAS site that is broken).

**Comment by rybesh** [comment]
Fixed by https://github.com/periodo/periodo-data/commit/fe0d849f7e44df6765860ca2a77b67696bfc0236
