### ISSUE TITLE
Language tags violate BCP47

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-data#30]
@hcayless pointed out on Twitter that our language tags are out of conformance. There are two issues:
1. [BCP47](https://tools.ietf.org/html/bcp47) decrees that for languages with both an ISO 639-1 (2-letter) tag and an ISO 639-3 (3-letter) tag, the shortest one **must** be used. So we can't use `deu` for German, we have to use `de`.
2. Although not strictly a part of the spec, BCP47 also discourages using script tags where they are unnecessary. So unless we expect to need to distinguish German sources written in the [Fraktur](https://en.wikipedia.org/wiki/Fraktur) script from those written in ordinary Latin script, we should drop the `-latn` from our tags. (In fact I'm not even sure we should have the script in there at all, for any of our language tags.)

**Comment by atomrab** [comment]
If we drop the script altogether, we will lose some important information
for eg Chinese, where language and script aren't 1:1, as we learned from
the CHGIS. This will also be an issue as we go back in time before language
reforms in eg Russian (I think, though I have to admit that I don't know if
pre-modernization script is given a separate designation).

Can we fix the language codes programmatically?

**Comment by ekansa** [comment]
I'm treating this as a situation with common defaults. Persian is written in the Arabic script by default, and Turkish is in the Latin script by default. So the assumption is if you see a Persian or Turkish language code, you assume the default script. You may want to only add script information if the script deviates from a default.

I'm not sure how this works with Japanese, which has a few scripts.

**Comment by hcayless** [comment]
This is a swamp, and I'm sorry if I've made your lives more complicated. http://www.w3.org/International/questions/qa-choosing-language-tags is a good outline of the problem. To be clear: my objection to the example @ekansa asked about wasn't that you were using ISO 639-3, but that the example, `deu-Latn`, was using the 3-character language code + a script code which, as @rybesh says above, isn't compliant with <https://tools.ietf.org/html/rfc5646>. `de-Latn` would be ok, but because the [subtag registry](http://www.iana.org/assignments/language-subtag-registry) says "Suppress-Script: Latn" for German, it's redundant. The script tags are very useful at times, however. Ancient Egyptian, for example, might be written in hieroglyphs (egy-Egyp), hieratic (egy-Egyh), or demotic (egy-Egyd). And then there's Coptic (cop), of course—same language, more or less, in yet another script (-Copt), but new language code, because reasons. I guess the objections to using ISO 639-3 would be that it may not be expressive enough by itself and the IANA registry is a going concern, so if you ran up against something new, you could get it added.

Like I said, it's a swamp: all the complexity of human language and writing systems, plus successive waves of attempts to codify them. Basically, you have to take them as they come and try to figure out what the best practices are for each language/region/script combo. https://r12a.github.io/apps/subtags/ is a useful lookup tool.

**Comment by rybesh** [comment]
@atomrab We can generate a patch programmatically and submit it like normal; that's not a big deal.

@ekansa As someone (Tom?) pointed out, the [`Suppress-Script`](https://tools.ietf.org/html/bcp47#section-3.1.9) field can be used to determine if the script tag is redundant. We can make the editing interface a little more intelligent so that it disables the script dropdown when it isn't relevant (i.e. a language with `Suppress-Script` is currently selected).

**Comment by rybesh** [comment]
Although I now notice that the IANA registry includes the `Suppress-Script` field for Japanese, so if we took the approach described above one could not separately specify _kanji_ and _hiragana_ labels for a period (since the `Suppress Script` field implies that Japanese is never written in only one of these scripts, always a mix of them—which is false).

Languages and time zones, two things engineers should never have been allowed near…

**Comment by rybesh** [comment]
As long as we're following pointless rules, we should probably also capitalize the first letter of the script tag (`Hira` not `hira`).

**Comment by VladimirAlexiev** [comment]
@rybesh Suppress-script only says which is default. It does in no way preclude you from specifying kanji or hiragana scripts.

**Comment by rybesh** [comment]
@VladimirAlexiev Thanks for the clarification. The case of Japanese is especially confusing because the value of `Suppress-Script` is `Jpan`, which is an alias for Han + Hiragana + Katakana (i.e. three different scripts). In other words, the default assumption is that Japanese is customarily written in more than one script, which is correct. However BCP47 says "The _lack_ [emphasis mine] of a 'Suppress-Script' might indicate that the language is customarily written in more than one script." 

Anyway, we're going to fix this to be in-line with the standards, I just enjoy kvetching about attempts to formalize the unformalizable…

**Comment by VladimirAlexiev** [comment]
Never worked with Japanese, but the way you describe it, there's never need to emit `Jpan`:
- if you know the script (and it's a single script), emit Han/Hiragana/Katakana
- else don't emit any script, since Jpan is default

**Comment by rybesh** [comment]
I have a data patch ready to go for this, but it can't be applied until [this pull request that fixes the language faceting in the client](https://github.com/periodo/periodo-client/pull/121) is merged. Also, we probably shouldn't bother patching the data until https://github.com/periodo/periodo-client/issues/113 is fixed.

**Comment by rybesh** [comment]
Fixed by https://github.com/periodo/periodo-server/pull/70

These changes have been deployed to https://staging.perio.do but not yet to the canonical server. However I am going to go ahead and close the bug.
